# Tarea día 8
**Programación I**

In [3]:
import numpy as np #importando numpy
import random

## Ejercicio 1

Cree una matriz que contenga ceros. Rellene la mitad de ellos aleatoriamente con unos.

In [4]:
M=np.zeros(100)
M[:50]=1
M

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.random.shuffle(M)
M

array([1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1.,
       1., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [6]:
J=M.reshape(10,10)
J

array([[1., 1., 0., 1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 1., 0., 1., 0., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 1., 1., 0., 1., 1.],
       [0., 0., 1., 1., 1., 0., 1., 0., 1., 1.],
       [1., 1., 0., 0., 1., 0., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1., 0., 1., 1., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [7]:
J.sum()

50.0

## Ejercicio 2
Cree dos matrices de dimensiones $(5,2)$. La primera rellena de ceros y la siguiente de unos. 
1.	Convierta las matrices en vectores columna. 
2.	Apile ambos vectores a lo largo de una tercera dimensión. 
3.	Con las matrices originales, conviértalas en vectores fila y concaténelos verticalmente. 



In [8]:
A=np.zeros([5,2])
B=np.ones([5,2])


In [33]:
A1=A.reshape(10,1)
A1

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [35]:
B1=B.reshape(10,1)
B1

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [42]:

C= np.concatenate((A1[None, :],B1[None, :]),axis=2)
C

array([[[0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.],
        [0., 1.]]])

In [43]:
C.ndim

3

In [167]:
AA=A.reshape(1,10)
AA

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [168]:
BB=B.reshape(1,10)
BB

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [166]:
np.vstack((AA,BB))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Ejercicio 3

Dada la función $f(x,y,z) = 2x +3y + z^2$
1.	Genere una matriz con números aleatorios para cada variable. 
2.	Evalúe la matriz anterior en la función. El resultado debe ser un vector columna. 

In [111]:
X=np.random.random(10)*10
Y=np.random.random(10)*10
Z=np.random.random(10)*10
X

array([2.30640802, 8.36888483, 6.04409331, 1.18460492, 7.25606351,
       6.66067216, 2.6248098 , 8.86494313, 8.98376417, 0.07015018])

In [112]:
Y

array([5.97310566, 3.8098704 , 6.95790465, 1.05909663, 0.91533403,
       5.02999574, 1.58112798, 0.94690324, 2.0177218 , 3.26443372])

In [113]:
Z

array([0.96549988, 3.8643856 , 6.23786887, 7.76121188, 0.81051749,
       6.21527489, 5.00180316, 3.55390782, 5.82403304, 1.03464732])

In [114]:
U=np.vstack((X,Y,Z))


In [115]:
U.T

array([[2.30640802, 5.97310566, 0.96549988],
       [8.36888483, 3.8098704 , 3.8643856 ],
       [6.04409331, 6.95790465, 6.23786887],
       [1.18460492, 1.05909663, 7.76121188],
       [7.25606351, 0.91533403, 0.81051749],
       [6.66067216, 5.02999574, 6.21527489],
       [2.6248098 , 1.58112798, 5.00180316],
       [8.86494313, 0.94690324, 3.55390782],
       [8.98376417, 2.0177218 , 5.82403304],
       [0.07015018, 3.26443372, 1.03464732]])

In [173]:
def f(x,y,z):
    return (2*x + 3*y + z**2)

In [174]:
S=f(X,Y,Z)
S.reshape(10,1)

array([[23.46432305],
       [43.1008569 ],
       [71.87290864],
       [65.78290959],
       [17.91506771],
       [67.04097344],
       [35.01103838],
       [33.20085675],
       [57.94005459],
       [11.00409659]])

## Ejercicio 4

Suponga que dentro de un cuadrado de lado 50 cm, hay un cuadrado de 20cm. Ambos cuadrados comparten centro. Estime el área del cuadrado interno por método Monte Carlo. [Consulte Aquí]( http://mathonweb.com/entrtain/monte/t_monte.htm)

**Caso esquina**

In [134]:
C50=np.random.randint(0,2,size=(50, 50))
C50

array([[1, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 1, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 1]])

In [123]:
C20= C50[-20:  ,0:20]
C20

array([[1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0],
       [0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1],
       [1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 1, 1, 0, 1, 1,

In [128]:
suma=sum(sum(C20))
suma


202

In [132]:
Area=(50*50)*(suma/(sum(sum(C50))))
Area

408.9068825910931

**Caso centro**

In [135]:
C50=np.random.randint(0,2,size=(50, 50))
C50

array([[1, 0, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 1, 0],
       ...,
       [1, 0, 1, ..., 1, 1, 0],
       [1, 0, 0, ..., 0, 0, 1],
       [0, 0, 1, ..., 0, 0, 0]])

In [137]:
C20= C50[15:35,15:35]
C20

array([[1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1],
       [1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0],
       [1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
       [1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1],
       [0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1],
       [1, 1, 0, 1, 0, 1, 0, 1, 0,

In [138]:
Area=(50*50)*(suma/(sum(sum(C50))))
Area

397.3249409913454

## Ejercicio 5

### *Tarea*

1. De las siguientes secciones, escoger 73 funciones de NumPy y mostrar su utilización en un ejemplo.

    - [Array creation routines](https://numpy.org/devdocs/reference/routines.array-creation.html)

    - [Array manipulation routines](https://numpy.org/devdocs/reference/routines.array-manipulation.html)

    - [Binary operations](https://numpy.org/devdocs/reference/routines.bitwise.html)

    - [String operations](https://numpy.org/devdocs/reference/routines.char.html)
    


1.1. **np.empty_like(prototype, dtype=None, order='K', subok=True, shape=None)**


Crea un nuevo array con el mismo tamaño y tipo que un array dado


In [141]:
a = np.array([[10, 10, 10],[2,4,8]])
b= np.empty_like(a)
a


array([[10, 10, 10],
       [ 2,  4,  8]])

In [143]:
b #la salida es generada con datos arbitrarios del mismo tipo y tamaño que el prototipo

array([[-1628784336,         487,           0],
       [          0,           1,           0]])

1.2. **np.full(shape, fill_value, dtype=None, order='C')**\


Crea un  array con tamaño y tipo , lleno del valor "fill_value"

In [149]:
np.full((5, 3), [1, 2,3])

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

1.3. **np.asarray(a, dtype=None, order=None)**

Convierte un input en un array.

In [150]:
b=[1,2,3,4,5,6,7,8,9]
np.asarray(b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

1.4. **np.fromstring(string, dtype=float, count=-1, sep='')**

Genera un array de una dimensión desde cadenas.


In [159]:
np.fromstring('2 5 6 7 8 3 9 9', dtype=int, sep=' ')


array([2, 5, 6, 7, 8, 3, 9, 9])

1.5. **np.loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None)**

Carga datos de un archivo .txt (Cada fila de texto deberá tener el mismo número de valores)

In [163]:
x = np.loadtxt("aa.txt", delimiter=',', usecols=(0, 1))
x

array([[ 4.,  5.],
       [ 5.,  5.],
       [ 6.,  4.],
       [ 6.,  6.],
       [ 7.,  5.],
       [ 8.,  5.],
       [ 9.,  5.],
       [10.,  5.],
       [11.,  4.],
       [11.,  6.],
       [12.,  5.],
       [13.,  5.]])

1.6. **np.chararray(shape, itemsize=1, unicode=False, buffer=None, offset=0, strides=None, order=None)**

Genera una visualización de una cadena como array

In [172]:
charar = np.chararray(charar.shape, itemsize=5)
charar[:] = 'abc'
charar


chararray([[b'abc', b'abc', b'abc'],
           [b'abc', b'abc', b'abc'],
           [b'abc', b'abc', b'abc']], dtype='|S5')

1.7. **np.logspace(start, stop, num=#de muestras, endpoint=True, base=10.0, dtype=None, axis=0)**

Genera numeros espaciados incluso en escala logarítmica

In [177]:
x1 = np.logspace(0.1, 1, 10, endpoint=True)
x1

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

1.8. **np.geomspace(start, stop, num=50, endpoint=True, dtype=None, axis=0)**

Genera números espaciados como una progresión geométrica.

In [178]:
np.geomspace(1, 1000, num=4)

array([   1.,   10.,  100., 1000.])

1.9. **linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)**

Regresa numeros espaciados indicando el inicio, final y cantidad de números a generar

In [188]:
nx, ny = (3, 2)
x = np.linspace(0, 1, nx)
y = np.linspace(2, 3, ny)
x

array([0. , 0.5, 1. ])

In [189]:
y

array([2., 3.])

1.10. **np.meshgrid(*xi, copy=True, sparse=False, indexing='xy')**

Regresa matriz que incluye dos vectores.

In [190]:
xv, yv = np.meshgrid(x, y)
xv

array([[0. , 0.5, 1. ],
       [0. , 0.5, 1. ]])

In [191]:
yv


array([[2., 2., 2.],
       [3., 3., 3.]])

In [192]:
w=np.meshgrid(x, y)
w



[array([[0. , 0.5, 1. ],
        [0. , 0.5, 1. ]]), array([[2., 2., 2.],
        [3., 3., 3.]])]

1.11. **n.diag(v,k=0)**

Extrae la diagonal de una  matriz.

In [193]:
x = np.arange(9).reshape((3,3))
x


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [194]:
np.diag(x)

array([0, 4, 8])

1.12. **np.diagflat(v, k=0)**

Crea una matriz diagonal a partir de un array  de dos dimensiones aplanado.

In [196]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

1.13. **np.tri(N(número de filas), M=número de columnas, k=0, dtype=<class 'float'>)**

Genera una matriz triangular. 

In [200]:
np.tri(3, 3, dtype=int)

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]])

1.14. **np.vander(x, N=número de columnas, increasing=True/False indica el orden en el que se colocan las potencias)**

Genera una matriz Vandermonde, las columnas de la matriz son las potencias del vector ingresado

In [201]:
x = np.array([1, 3, 5, 7])
np.vander(x)


array([[  1,   1,   1,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1],
       [343,  49,   7,   1]])

1.15. **np.mat(data, dtype=None)**

Interpreta el input como una matriz.

In [203]:
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
m

matrix([[1, 2],
        [3, 4]])

1.16. **np.bmat(obj, ldict=None, gdict=None)**

Construye un objeto matriz mediante una cadena, secuencia anidada o array.

In [204]:
A = np.mat('1 1; 1 1')
B = np.mat('2 2; 2 2')
C = np.mat('3 4; 5 6')
D = np.mat('7 8; 9 0')
E = np.bmat([[A, B], [C, D]])
E

matrix([[1, 1, 2, 2],
        [1, 1, 2, 2],
        [3, 4, 7, 8],
        [5, 6, 9, 0]])

1.17. **np.moveaxis(a, source, destination)**

Mueve los ejes de un array en nuevas posiciones, el resto de los ejes mantienen sus posiciones originales.


In [206]:
x = np.zeros((3, 4, 5))
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [207]:
np.moveaxis(x, 0, -1)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

1.18. **np.rollaxis(a, axis, start=0)**

Rota el eje especifico hacia atrás hasta que se encuentre en la posición deseada.

In [220]:
a = np.ones((3,4,5,6))
a

array([[[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
        

In [225]:
np.rollaxis(a,3,0).shape

(6, 3, 4, 5)

1.19. **np.swapaxes(a, axis1, axis2)**

Intercambia dos ejes de un array.

In [226]:
x = np.array([[1,2,3]])
np.swapaxes(x,0,1)


array([[1],
       [2],
       [3]])

1.20. **np.atleast_1d(*arys)**

Convierte el input en arrays de al menos una dimensión.

In [227]:
x = np.arange(9.0).reshape(3,3)
np.atleast_1d(x)


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

1.21. **np.expand_dims(a, axis)**

Expande la forma del array. Inserta un nuevo eje en la posición en la que se expande.

In [228]:
x = np.array([1, 2])
x.shape


(2,)

In [230]:
y = np.expand_dims(x, axis=0)
y



array([[1, 2]])

1.22. **np.squeeze(a, axis=None)**

Remueve las dimensiones en la forma del array.

In [236]:
x = np.array([[[0], [1], [2]]])
x.shape

(1, 3, 1)

In [237]:
np.squeeze(x).shape

(3,)

1.23. **np.asscalar(a)**

Convierte un array de dimensión 1 a su escalar equivalente.



In [238]:
np.asscalar(np.array([24]))


24

1.24. **np.concatenate((a1, a2, ...), axis=0, out=None)**

Combina una secuencia de arrayz en un eje existente.

In [239]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
c=np.concatenate((a, b), axis=0)


In [240]:
a

array([[1, 2],
       [3, 4]])

In [241]:
b

array([[5, 6]])

In [242]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

1.25. **np.stack(arrays, axis=0, out=None)**

Combina una secuencia de arrays en un nuevo eje

In [243]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.stack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

1.26. **numpy.column_stack(tup)**

stack arrays de una dimensión como columnas en un array de dos dimensiones.

In [244]:
a = np.array((1,2,3))
b = np.array((2,3,4))
c= np.column_stack((a,b))
c


array([[1, 2],
       [2, 3],
       [3, 4]])

1.27. **np.dstack(tup)** 

Stack arrays en una secuencia depth wise(en el tercer eje). 

In [245]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
c= np.dstack((a,b))
c


array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

1.28. ****np.hstack(tup)****

Stack arrays en una secuencia horizontal (column wise).

In [246]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
np.hstack((a,b))


array([[1, 2],
       [2, 3],
       [3, 4]])

1.29. **np.hstack(tup)** 

Stack arrays en una secuencia vertical (row wise)

In [247]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
c= np.vstack((a,b))
c


array([[1],
       [2],
       [3],
       [2],
       [3],
       [4]])

1.30. **np.block(array)**

Une un array de dimensión n, mediante listas anidadas de bloques. 

In [248]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
c= np.block([a, b, 10]) 
c

array([ 1,  2,  3,  2,  3,  4, 10])

1.31. **np.split(ary, indices_or_sections, axis=0)**

Divide un array en multiples sub-arrays del mismo tamaño.

In [249]:
x = np.arange(9.0)
np.split(x, 3)


[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

1.32. **np.array_split(ary, indices_or_sections, axis=0)**

Divide un array en multiples sub-arrays.

In [250]:
x = np.arange(7.0)
np.array_split(x, 3)


[array([0., 1., 2.]), array([3., 4.]), array([5., 6.])]

1.33. **np.dsplit(ary, indices_or_sections)** 

Divide un array en multiples sub-arrays en el tercer eje.

In [251]:
 x = np.arange(16.0).reshape(2, 2, 4)
x


array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [252]:
np.dsplit(x, np.array([3, 6]))

[array([[[ 0.,  1.,  2.],
         [ 4.,  5.,  6.]],
 
        [[ 8.,  9., 10.],
         [12., 13., 14.]]]), array([[[ 3.],
         [ 7.]],
 
        [[11.],
         [15.]]]), array([], shape=(2, 2, 0), dtype=float64)]

1.34. **np.hsplit(ary, indices_or_sections)** 

Divide un array en sub-arrays horizontales.

In [253]:
x = np.arange(8.0).reshape(2, 2, 2)
x


array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [254]:
np.hsplit(x, 2)


[array([[[0., 1.]],
 
        [[4., 5.]]]), array([[[2., 3.]],
 
        [[6., 7.]]])]

1.35. **np.hsplit(ary, indices_or_sections)** 

Divide un array en sub-arrays verticales.

In [256]:
x = np.arange(8.0).reshape(2, 2, 2)
x


array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [257]:
np.vsplit(x, 2)


[array([[[0., 1.],
         [2., 3.]]]), array([[[4., 5.],
         [6., 7.]]])]

1.36. **numpy.tile(A, reps)**

Construye un array mediante la repetición de un array de referencia dado un número de repeticiones.

In [258]:
a = np.array([0, 1, 2])
np.tile(a, 2)


array([0, 1, 2, 0, 1, 2])

1.37. **numpy.repeat(a, repeats, axis=None)** 

Repite los elementos de un array.

In [259]:
x = np.array([[1,2],[3,4]])
np.repeat(x, 2)


array([1, 1, 2, 2, 3, 3, 4, 4])

1.38. **np.insert(arr, obj=indica antes de que valor debe insertarse el valor, values, axis=None)** 

Inserta valores a lo largo de un eje dado, antes del indice indicado.

In [260]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a


array([[1, 1],
       [2, 2],
       [3, 3]])

In [262]:
np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

1.39. **np.append(arr, values, axis=None)** 

Agrega valores al final del array.

In [263]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

1.40. **np.resize(a, new_shape)**

Construye un nuevo array de la forma especificada.

In [264]:
a=np.array([[0,1],[2,3]])
np.resize(a,(2,3))


array([[0, 1, 2],
       [3, 0, 1]])

1.41. **np.trim_zeros(filt, trim='fb')**

Recorta el número de ceros de una secuencia.

In [265]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))
np.trim_zeros(a)


array([1, 2, 3, 0, 2, 1])

1.42. **numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)**

Encuentra los elementos unicos en un array.

In [267]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

1.43. **np.delete(arr, obj, axis=None)** 

Un nuevo array con sub-arrays eliminadas.

In [268]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [269]:
np.delete(a, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

1.44. **np.flip(m, axis=None)**

Revierte el orden de los elementos en un array a lo largo de un eje específico.

In [272]:
A = np.arange(8).reshape((2,2,2))
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [271]:
np.flip(A, 0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

1.45. **np.fliplr(m)**

Intercambia (da la vuelta) el array en la dirección derecha/izquierda.

In [273]:
A = np.diag([1.,2.,3.])
A


array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [274]:
np.fliplr(A)

array([[0., 0., 1.],
       [0., 2., 0.],
       [3., 0., 0.]])

1.46. **numpy.flipud(m)**
Intercambia (da la vuelta) el array en la dirección arriba/abajo.


In [275]:
A = np.diag([1.0, 2, 3])
A

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [276]:
np.flipud(A)

array([[0., 0., 3.],
       [0., 2., 0.],
       [1., 0., 0.]])

1.47. **np.roll(a, shift, axis=None)** 

Gira los elementos del array en un eje dado, indicando el punto donde se gira.


In [277]:
x = np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [278]:
np.roll(x, 2)

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

1.48. **numpy.rot90(m, k=1, axes=(0, 1))**

Rota un array en 90 grados en un plano especificado por los ejes.

In [279]:
 m = np.array([[1,2],[3,4]], int)
m


array([[1, 2],
       [3, 4]])

In [280]:
np.rot90(m)


array([[2, 4],
       [1, 3]])

1.49. **numpy.char.capitalize(a)**

Regresa una copia de la cadena con el primer elemento en mayúscula.


In [282]:
c = np.array(['a1b2','1b2a','b2a1','2a1b'],'S4')
c

array([b'a1b2', b'1b2a', b'b2a1', b'2a1b'], dtype='|S4')

In [283]:
np.char.capitalize(c)

array([b'A1b2', b'1b2a', b'B2a1', b'2a1b'], dtype='|S4')

1.50. **np.char.add(x1, x2)**

Regresa la concatenación de dos cadenas.


In [290]:
x=np.array(["Hola ","Adiós "])
y=np.array(["amigo"])
np.char.add(x,y)

array(['Hola amigo', 'Adiós amigo'], dtype='<U11')

1.51. **np.char.multiply(a, i)**

Genera una concatenación multiple de una cadena.

In [292]:
np.char.multiply("Hola ",5)

array('Hola Hola Hola Hola Hola ', dtype='<U25')

1.52. **np.char.center(a, width, fillchar=' ')**

Genera una copia de la cadena con sus elementos centrados en una cadena de longitud dada.

In [294]:
np.char.center("Atentamente",20)

array('    Atentamente     ', dtype='<U20')

1.53. **np.char.expandtabs(a, tabsize=8)**

Genera una copia de cada elemento de la cadena donde todos los caracteres de separación se reemplazan por uno o más espacios.

In [297]:
np.char.expandtabs('Geeks\tFor\tGeeks',tabsize=2)

array('Geeks For Geeks', dtype='<U15')

1.54. **np.char.join(sep, seq)**

Concatenación de una secuencia de los elementos de una cadena con otra.

In [300]:
np.char.join('Hola','am')

array('aHolam', dtype='<U6')

1.55. **np.char.lower(a)**

Genera una copia de la cadena en minúsculas.

In [301]:
np.char.lower("Hola")

array('hola', dtype='<U4')

1.56. **np.char.lstrip(a, chars=None)** 

Para cada elemento en la cadena, genera una copia con los caracteres iniciales removidos.

In [302]:
np.char.lstrip('Hola','H')

array('ola', dtype='<U4')

1.57. **np.char.partition(a, sep)**

Genera una partición de cada elemento en el array en el separador sep.

In [303]:
x=np.array(["Hola ","Adiós "])
np.char.partition(x,'a')

array([['Hol', 'a', ' '],
       ['Adiós ', '', '']], dtype='<U6')

1.58. **np.char.replace(a, old, new, count=None)**

Para cada elemento en a, genera una copia de la cadena con todas las ocurrencias de la cadena sustituidas.

In [307]:
x=np.array(["Hola amigos","Adiós amigos"])
np.char.replace(x,'a','e')

array(['Hole emigos', 'Adiós emigos'], dtype='<U12')

1.59. **np.char.rsplit(a, sep=None, maxsplit=None)**

Para cada elemento en a, devuelve una lista de las palabras en la cadena, usando sep como delimitador de la cadena.

In [308]:
x=np.array(["Hola amigos","Adiós amigos"])
np.char.rsplit(x, sep=None, maxsplit=None)

array([list(['Hola', 'amigos']), list(['Adiós', 'amigos'])], dtype=object)

1.60. **np.char.strip(a, chars=None)**

Para cada elemento en a, devuelve una copia con las letras iniciales y finales removidas.

In [309]:
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
c

array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')

In [310]:
np.char.strip(c, 'a')

array(['AaAaA', '  aA  ', 'bBABb'], dtype='<U7')

1.61. **np.char.swapcase(a)**

Devuelve una copia con las mayúsculas y minúsculas intercambiadas.

In [311]:
np.char.swapcase('HoLa')

array('hOlA', dtype='<U4')

1.62. **np.char.upper(a)**

Devuelve el array con los elementos en mayúsculas

In [312]:
np.char.upper('Amigos')

array('AMIGOS', dtype='<U6')

1.63. **np.char.zfill**

Devuelve una cadena numérica con ceros a la izquierda

In [319]:
x=np.array(['1','20','3124','422','5'])
x

array(['1', '20', '3124', '422', '5'], dtype='<U4')

In [320]:
np.char.zfill(x,4)

array(['0001', '0020', '3124', '0422', '0005'], dtype='<U4')

1.64. **np.char.equal(x1, x2)**

Compara dos arrays elemento a elemento.

In [321]:
x=np.array(['1','20','3124','422','5'])
y=np.array(['1','21','3124','422','5'])
np.char.equal(x,y)

array([ True, False,  True,  True,  True])

1.65. **np.char.count(a, sub, start=0, end=None)** 

Devuelve un array con el numero de las ocurrencias de letras en una cadena.

In [335]:
c = np.array(['aAaAaA', '  aA  ', 'abBABba'])
c

array(['aAaAaA', '  aA  ', 'abBABba'], dtype='<U7')

In [324]:
np.char.count(c, 'A')

array([3, 1, 1])

1.66. **np.char.find(a, sub, start=0, end=None)**

Para cada elemento, devuelve el menor índice en el que la cadena tiene una subcadena.

In [332]:
np.char.find('Hello World','Amigo' ,start=0, end=None)

array(-1)

1.67. **np.char.index(a, sub, start=0, end=None)¶**

Encuentra el indice de una subcadena en una cadena de texto

In [333]:
np.char.index('Hello World','World' ,start=0, end=None)

array(6)

1.68. **np.char.isdecimal(a)**

Para cada elemento devuelve "True" si hay solo decimales en el elemento.

In [339]:
x=np.array(['0.20','0.10'])
np.char.isdecimal(x)

array([False, False])

1.67. **np.char.str_len(a)**
Devuelve la longitud de cada elemento

In [340]:
np.char.str_len(x)

array([4, 4])

1.68. **numpy.bitwise_and(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'bitwise_and'>**


In [341]:
np.bitwise_and(13, 17)

1

1.69. **numpy.bitwise_or(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj]) = <ufunc 'bitwise_or'>**


In [343]:
np.bitwise_or([33, 4], 1)


array([33,  5], dtype=int32)

1.70. **numpy.binary_repr(num, width=None**

Devuelve la representación binaria de un número o cadena.

In [344]:
np.binary_repr(3)

'11'

1.71. **numpy.base_repr(number, base=2, padding=0)**

Devuelve la representación en cadena de un número.

In [345]:
np.base_repr(5)

'101'

1.72. **numpy.shape(a)**

Devuelve la forma del array.

In [349]:
a = np.array([(1, 2), (3, 4)])
np.shape(a)

(2, 2)

1.73. **numpy.empty_like(prototype, dtype=None, order='K', subok=True, shape=None)**

Devuelve un array con la misma forma y tipo que el array dado.


In [350]:
a = ([1,2,3], [4,5,6])                        
np.empty_like(a)


array([[-1628784336,         487,           0],
       [          0,           1, -2147483648]])


2. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo binario `.npy` y `.npz`:

    - [NumPy binary files (NPY, NPZ)](https://numpy.org/devdocs/reference/routines.io.html#numpy-binary-files-npy-npz)
    


**Guardar y cargar arreglos de un archivo binario**

***NPY***

In [361]:
A = np.array((1,2,3,4,5,6,7))
np.save('prueba',A)

In [363]:
m=np.load('prueba.npy')
m

array([1, 2, 3, 4, 5, 6, 7])

***NPZ***

In [374]:
A = np.array((1,2,3,4,5,6,7))
B = np.array((1,4,9,16,25,36,49))

np.savez('prueba2.bin', A1= A, B1 = B)

In [375]:
entrada = np.load('prueba.bin.npz')

In [376]:
entrada['A1']

array([1, 2, 3, 4, 5, 6, 7])

In [377]:
entrada['B1']

array([ 1,  4,  9, 16, 25, 36, 49])

3. Crear un ejemplo de cómo guardar y cargar arreglos de un archivo de texto `.txt`:

    - [NumPy Text files](https://numpy.org/devdocs/reference/routines.io.html#text-files)    
    


**Guardar y cargar arreglos de un archivo de texto**

In [364]:
M = np.linspace(0, 2*np.pi, 20)
N = np.random.random((10,10))
np.savetxt('Guardartxt', M, delimiter=',')   

In [366]:
np.loadtxt('Guardartxt', delimiter=',')

array([0.        , 0.33069396, 0.66138793, 0.99208189, 1.32277585,
       1.65346982, 1.98416378, 2.31485774, 2.64555171, 2.97624567,
       3.30693964, 3.6376336 , 3.96832756, 4.29902153, 4.62971549,
       4.96040945, 5.29110342, 5.62179738, 5.95249134, 6.28318531])

4. Crear una función llamada `estimacionMCO` que lea un archivo CSV con 7 columnas, que corresponden a las variables $(x_{1i}, \ldots, x_{6i})$ y $y_i$. 
    - La función debe computar matricialmente los parámetros del modelo de regresión lineal: $y = X\beta$. 
    - Estos parámetros deben ser devueltos como un arreglo de NumPy. 

    - Utilice la función de lectura de archivos de NumPy.

In [409]:
def estimacionMCO():
    nombre_archivo=str(input("Ingrese valores en archivo .csv: "))+".csv"
    datos=np.genfromtxt(nombre_archivo,delimiter=',')
    X=datos[: , :6]
    Y=datos[:,6:7]
    A=(X.T)@X
    B=((X.T)@Y)
    betas=((np.linalg.inv(A))@B)
    return betas

In [410]:
estimacionMCO()

Ingrese valores en archivo .csv: datos


array([[0.24224286],
       [0.22390316],
       [0.04160828],
       [0.09023944],
       [0.19057616],
       [0.12859507]])